### PR TITLE
Dataset Variable handling + ODK Handling

### PR DESCRIPTION
**Pull request by dave-mills**
This PR does 2 things:

### Updates basic support for 'dataset variables': 

 - `DatasetVariable::class` now has the correct relationships to `Entity::class` and `Dataset::class`. (This is used in the tape-data-system to allow us to update the variables for the Agricultural Systems).
 
### Adds better handling of link to ODK / errors

- Previously, you would get errors for lots of things (including running migrations!) if you had not added valid ODK_ environment variables to a real ODK Central server. 
- Now, you can install the package just fine and run the app without connecting to ODK Central. When there are no env credentials:
   - The XlsformTemplateResource  shows a warning notice explaining that you cannot upload forms.
   - Creation of entities that use HasXlsforms (e.g., Teams, platforms), do not trigger an attempt to create a project on ODK Central. 

Additionally, there is now a better approach to creating the required Platform::class entry: 

- previously, this was done in the migration. 
- This is now moved to a separate seeder (following good practice to only use migrations for structural database changes). This seeder should be run as part of the main application seeding (e.g: 

`database/seeders/DatabaseSeeder.php`:  

```php

use Illuminate\Database\Seeder;
use Stats4sd\FilamentOdkLink\Database\Seeders\PlatformSeeder;

class DatabaseSeeder extends Seeder
{

    public function run(): void
    {
         $this->call(PlatformSDeeder::class);
    }

}


```

This seeder will create the Platform::class entry. If there is no ODK_PLATFORM_PROJECT_ID env variable, it will take the normal approach, which includes going to ODK Central and creating a new project. It will then set the ODK_PLATFORM_PROJECT_ID to that project ID. 

When you run the seeder a second time, it will check that same variable, and will not create a 2nd project on ODK Central. It will instead link the new platform entry to the existing project. 

This saves the creation of multiple copies of test projects as you run `php artisan migrate:fresh` lots of times in local development.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Thank you Dave.

I did testing a few times to figure out the correct procedure for setup, I found two issues:

1. The seeder file has not been published. (How to publish a seeder file from submodule? It looks like Service Provider does not provide this feature... Should we change the seeder file to the last migration file in submodule?)

2. If ODK central config items are empty in .env file. Team seeder file will throw error because it talks to ODK central when creating a Team. I can login but filament will prompt to create a new team because the logged in user does not belong to any team. Team cannot be created successfully in front end because ODK central config items in .env file. The logged in user will stuck here. He will have no chance to see the newly added warning notice in front end.

---

Here is my testing procedure details FYI:

cd c:\public

git clone https://github.com/stats4sd/apni-research apni-research-v3

cd apni-research-v3

git submodule init

git submodule update

cd packages

cd filament-odk-link

git checkout dataset-variables

git pull

create local database

prepare .env file
 - update local db config items
 - copy Laravel Reverb config items
 - do not fill in values for ODK central config items

composer install

php artisan key:generate

npm i

npm run build

npm run dev

remove create platform migration files in main repo (I pushed them to main repo before...)

run command to publish migration files from submodule
 - php artisan vendor:publish --tag="filament-odk-link-migrations"

the latest create platform migration file is published

remove the duplicated create_permission_tables migration file

refresh database with migration files and run seeders
 - php artisan migrate:fresh --seed
 - cURL error when running Teams seeder
  - it talks to ODK central to create ODK project when creating Team

http://apni-research-v3.test

login as test@example.com

Team has not been created yet (because there is no ODK central config items in .env file)
User does not belong to any team, filament prompt to create a new team
 - cURL error when creating Team...

The logged in user will stuck here. He will have no chance to see the newly added warning notice in front end.

**Comment by dan-tang-ssd** [comment]
I read all modified program source code in this PR. Now I have a better understanding for this change.

I did some minor refinements, mainly to take care config item existence and empty config item.

Basically it works well, migration files and seeder files can be executed without ODK link config items (or they are empty) in .env file. The warning notice can be showed nicely.

Some pages show error due to appUsers (actually it is because odkProject is null) but it is expected. I think we do not need to further handle, suppose the application should connect to a valid ODK central server.

By adding ODK central config items and values in .env file, all migration files and seeder files executed successfully.
When I login as admin account, there is one minor issue in below page:
Admin Panel > Teams list page > View a team > error occurred

If I run "php artisan migrate:fresh --seed", there is no app_users record created for Platform for odk_projects record

---

By the way, here are something need to be handled:

1. When I setup main repo APNI Research, I pushed the previously published migration files from submodule. They are in main repo now. For my testing, I manually removed them and then publish submodule migration files for testing. (P.S. Still need to remove create permissions migration file)

2. In main repo, there are some migration files to be executed after running submodule migration files. Currently I renamed the date part in migration files to make them in correct seqeunce. Not sure how to make it work for a formal setup...

3. In main repo, I pushed a previously published submodule config file, we will need to remove it in main repo

4. In DatabaseSeeder.php, I cannot refer to seeder file in submodule. I copied the seeder file from submodule to main repo, then add it in DatabaseSeeder.php, then the seeder file can run.

**Comment by dan-tang-ssd** [comment]
There is a change in main repo for App\Models\Team.php, to remove code for odkLinkService and createLinkedOdkProject. (Because these will be centrally handled by HasXlsForms trait.

I did not commit the change yet as I accidentally commit to dev (luckily I did not run "git push" yet). I will undo my local commit and push my change in a new branch of main repo.

**Comment by dave-mills** [comment]
Thanks Dan - useful review and updates to the PlatformSeeder. I've made a few last tweaks (to handle cases where the project id environment variable is present but an empty string *or* where the variable doesn't exist at all).

> 1. When I setup main repo APNI Research, I pushed the previously published migration files from submodule. They are in main repo now. For my testing, I manually removed them and then publish submodule migration files for testing. (P.S. Still need to remove create permissions migration file)

👍 . Makes sense. I typically will update the migration files in the migration file to get them working, then copy them back into the package to update them. Your approach works well too, though you're right you then get some possible ordering issues. 

> 2. In main repo, there are some migration files to be executed after running submodule migration files. Currently I renamed the date part in migration files to make them in correct seqeunce. Not sure how to make it work for a formal setup...

I think in a formal setup, devs would publish the migration files from the package when needed, and won't be re-publishing them, so there won't be these ordering issues we see from developing the package itself and re-publishing.

> 3. In main repo, I pushed a previously published submodule config file, we will need to remove it in main repo

Or update it! Depends if you had made changes to it or not. 

> 4. In DatabaseSeeder.php, I cannot refer to seeder file in submodule. I copied the seeder file from submodule to main repo, then add it in DatabaseSeeder.php, then the seeder file can run.

That's odd. It works for me on the tape-data-system (code as above, also [here](https://github.com/stats4sd/tape-data-system/blob/1bf94acbcdcdd08cba00eb3f32e67772f06ccc9b/database/seeders/DatabaseSeeder.php#L8) )

This looks good - is this good to merge?

**Pull request merged**
